const { config } = require('dotenv');
const { writeFile, existsSync, mkdirSync } = require('fs');
const { argv } = require('yargs');

function writeFileUsingFS(targetPath: string, content: string) { 
  writeFile(targetPath, content, (err: any) => {
    if (err) {
        console.log(err);
    }
  });
}

config();

const environment = (argv as any).environment;
const isProd = environment === 'prod';
const envDir = './src/environments';
const targetPath = isProd ? './src/environments/environment.prod.ts' : './src/environments/environment.ts'
const content = `
// This file is autogenerated during compile time to secure api keys
export const environment = {
  production: ${isProd},

  accuWeatherBaseURL: 'https://dataservice.accuweather.com/forecasts/v1',
  accuWeatherApiKey: '${process.env["ACCU_WEATHER_API_KEY"]}',
  accuWeatherCityKey: '168717',

  googleCalendarBaseURL: ["https://www.googleapis.com/discovery/v1/apis/calendar/v3/rest"],
  googleClientId: '${process.env["GOOGLE_CALENDAR_CLIENT_ID"]}',
  googleApiKey: '${process.env["GOOGLE_API_KEY"]}',
  googleCalendarScope: 'https://www.googleapis.com/auth/calendar.readonly'
};
`;

if (!existsSync(envDir)) {
  mkdirSync(envDir);
}

writeFileUsingFS('./src/environments/environment.prod.ts', '');
writeFileUsingFS('./src/environments/environment.ts', '');

writeFileUsingFS(targetPath, content);
