name: CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  pre-build:
    name: Build Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Extract version from package.json
        id: version
        run: |
          PACKAGE_VERSION=v$(cat ./package.json | jq '.version' | tr -d '"')
          echo ::set-output name=current-version::$PACKAGE_VERSION
    outputs:
      version: ${{ steps.version.outputs.current-version }}

  build-package:
    name: Pre-Build package
    runs-on: ubuntu-latest
    needs: [ pre-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Build Angular
        run: npm run build
      - name: Create release artifact
        run: npm run compress
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "smart-mirror.tar.gz"
          body: "A new awesome release!"
          tag: ${{ needs.pre-build.outputs.version }}
          skipIfReleaseExists: true

  build-docker:
    name: Docker 
    runs-on: ubuntu-latest
    needs: [ pre-build ]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1.3
        with:
          envkey_ACCU_WEATHER_API_KEY: ${{ secrets.ACCU_WEATHER_API_KEY }}
          envkey_GOOGLE_CALENDAR_CLIENT_ID: ${{ secrets.GOOGLE_CALENDAR_CLIENT_ID }}
          envkey_GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      - name: Build the Docker image
        uses: whoan/docker-build-with-cache-action@v5
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          image_name: k-r-i-s-t-a/smart-mirror
          image_tag: ${{ needs.pre-build.outputs.version }}
